# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:42:49+00:00



import argparse
import json
import os
from typing import *

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyHeader, APIKeyQuery, BaseSecurity
from fastapi import Path

from models import (
    DfsSlateWithOwnershipProjection,
    FieldFormatDfsSlatesByDateDateGetResponse,
    FieldFormatDfsSlatesByWeekSeasonWeekGetResponse,
    FieldFormatFantasyDefenseProjectionsByGameSeasonWeekGetResponse,
    FieldFormatFantasyDefenseProjectionsBySeasonSeasonGetResponse,
    FieldFormatIdpPlayerGameProjectionStatsByTeamSeasonWeekTeamGetResponse,
    FieldFormatIdpPlayerGameProjectionStatsByWeekSeasonWeekGetResponse,
    FieldFormatInjuredPlayersGetResponse,
    FieldFormatPlayerGameProjectionStatsByTeamSeasonWeekTeamGetResponse,
    FieldFormatPlayerGameProjectionStatsByWeekSeasonWeekGetResponse,
    FieldFormatPlayerSeasonProjectionStatsByTeamSeasonTeamGetResponse,
    FieldFormatPlayerSeasonProjectionStatsSeasonGetResponse,
    FieldFormatUpcomingDfsSlateOwnershipProjectionsGetResponse,
    Format,
    PlayerGameProjection,
    PlayerSeasonProjection,
)

app = MCPProxy(
    contact={'x-twitter': 'nfldata'},
    description='NFL projected stats API.',
    title='NFL v3 Projections',
    version='1.0',
    servers=[
        {'url': 'http://azure-api.sportsdata.io/v3/nfl/projections'},
        {'url': 'https://azure-api.sportsdata.io/v3/nfl/projections'},
    ],
)


@app.get(
    '/{format}/DfsSlateOwnershipProjectionsBySlateID/{slateId}',
    description=""" Slate Ownership Projections for a specific slate. Projections are for GPP format ownership. Will return an empty list if the slate is not yet projected or not a slate we have projections for. """,
    tags=['dfs_slate_management'],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def dfs_slate_ownership_projections_by_slateid(
    format: Format = 'XML', slate_id: str = Path(..., alias='slateId')
):
    """
    DFS Slate Ownership Projections by SlateID
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/{format}/DfsSlatesByDate/{date}',
    tags=['dfs_slate_management'],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def dfs_slates_by_date(format: Format = 'XML', date: str = ...):
    """
    DFS Slates by Date
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/{format}/DfsSlatesByWeek/{season}/{week}',
    tags=['dfs_slate_management'],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def dfs_slates_by_week(format: Format = 'XML', season: str = ..., week: str = ...):
    """
    DFS Slates by Week
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/{format}/FantasyDefenseProjectionsByGame/{season}/{week}',
    tags=['dfs_slate_management', 'fantasy_defensive_statistics'],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def projected_fantasy_defense_game_stats_w_dfs_salaries(
    format: Format = 'XML', season: str = ..., week: str = ...
):
    """
    Projected Fantasy Defense Game Stats (w/ DFS Salaries)
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/{format}/FantasyDefenseProjectionsBySeason/{season}',
    tags=['fantasy_defensive_statistics', 'player_season_projection_stats'],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def projected_fantasy_defense_season_stats_w_adp(
    format: Format = 'XML', season: str = ...
):
    """
    Projected Fantasy Defense Season Stats (w/ ADP)
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/{format}/IdpPlayerGameProjectionStatsByPlayerID/{season}/{week}/{playerid}',
    tags=['individual_defensive_player_stats', 'injury_impact_analysis'],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def idp_projected_player_game_stats(
    format: Format = 'XML', season: str = ..., week: str = ..., playerid: str = ...
):
    """
    IDP Projected Player Game Stats by Player (w/ Injuries, Lineups, DFS Salaries)
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/{format}/IdpPlayerGameProjectionStatsByTeam/{season}/{week}/{team}',
    tags=[
        'individual_defensive_player_stats',
        'injury_impact_analysis',
        'dfs_slate_management',
    ],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def idp_projected_player_stats_by_team(
    format: Format = 'XML', season: str = ..., week: str = ..., team: str = ...
):
    """
    IDP Projected Player Game Stats by Team (w/ Injuries, Lineups, DFS Salaries)
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/{format}/IdpPlayerGameProjectionStatsByWeek/{season}/{week}',
    tags=['individual_defensive_player_stats', 'injury_impact_analysis'],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def idp_projected_player_game_stats_by_week(
    format: Format = 'XML', season: str = ..., week: str = ...
):
    """
    IDP Projected Player Game Stats by Week (w/ Injuries, Lineups, DFS Salaries)
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/{format}/InjuredPlayers',
    description=""" This endpoint provides all currently injured NFL players, along with injury details. """,
    tags=['injury_impact_analysis', 'individual_defensive_player_stats'],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def injured_players(format: Format = 'XML'):
    """
    Injured Players
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/{format}/PlayerGameProjectionStatsByPlayerID/{season}/{week}/{playerid}',
    tags=[
        'dfs_slate_management',
        'injury_impact_analysis',
        'player_season_projection_stats',
    ],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def projected_player_stats_with_injuries_and_dfs_salaries(
    format: Format = 'XML', season: str = ..., week: str = ..., playerid: str = ...
):
    """
    Projected Player Game Stats by Player (w/ Injuries, Lineups, DFS Salaries)
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/{format}/PlayerGameProjectionStatsByTeam/{season}/{week}/{team}',
    tags=[
        'dfs_slate_management',
        'injury_impact_analysis',
        'player_season_projection_stats',
    ],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def projected_player_stats_by_team_with_injuries(
    format: Format = 'XML', season: str = ..., week: str = ..., team: str = ...
):
    """
    Projected Player Game Stats by Team (w/ Injuries, Lineups, DFS Salaries)
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/{format}/PlayerGameProjectionStatsByWeek/{season}/{week}',
    tags=[
        'dfs_slate_management',
        'injury_impact_analysis',
        'player_season_projection_stats',
    ],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def projected_player_stats_by_week_with_injuries(
    format: Format = 'XML', season: str = ..., week: str = ...
):
    """
    Projected Player Game Stats by Week (w/ Injuries, Lineups, DFS Salaries)
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/{format}/PlayerSeasonProjectionStats/{season}',
    tags=['player_season_projection_stats', 'fantasy_defensive_statistics'],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def projected_player_season_stats_w_adp(format: Format = 'XML', season: str = ...):
    """
    Projected Player Season Stats (w/ ADP)
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/{format}/PlayerSeasonProjectionStatsByPlayerID/{season}/{playerid}',
    tags=['player_season_projection_stats', 'fantasy_defensive_statistics'],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def projected_player_season_stats_by_player_w_adp(
    format: Format = 'XML', season: str = ..., playerid: str = ...
):
    """
    Projected Player Season Stats by Player (w/ ADP)
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/{format}/PlayerSeasonProjectionStatsByTeam/{season}/{team}',
    tags=['player_season_projection_stats', 'fantasy_defensive_statistics'],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def projected_player_season_stats_by_team_w_adp(
    format: Format = 'XML', season: str = ..., team: str = ...
):
    """
    Projected Player Season Stats by Team (w/ ADP)
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/{format}/UpcomingDfsSlateOwnershipProjections',
    description=""" Grabs DFS Slates which have not yet started for which we have DFS Ownership projections.  """,
    tags=['dfs_slate_management'],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def upcoming_dfs_slate_ownership_projections(format: Format = 'XML'):
    """
    Upcoming DFS Slate Ownership Projections
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
