# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:42:49+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, RootModel


class DfsSlatePlayer(BaseModel):
    FantasyDefenseProjectionStatID: Optional[int] = None
    OperatorPlayerID: Optional[str] = None
    OperatorPlayerName: Optional[str] = None
    OperatorPosition: Optional[str] = None
    OperatorRosterSlots: Optional[List[str]] = None
    OperatorSalary: Optional[int] = None
    OperatorSlatePlayerID: Optional[str] = None
    PlayerGameProjectionStatID: Optional[int] = None
    PlayerID: Optional[int] = None
    RemovedByOperator: Optional[bool] = None
    SlateGameID: Optional[int] = None
    SlateID: Optional[int] = None
    SlatePlayerID: Optional[int] = None
    Team: Optional[str] = None
    TeamID: Optional[int] = None


class DfsSlatePlayerOwnershipProjection(BaseModel):
    FantasyDefensePlayerID: Optional[int] = None
    IsCaptain: Optional[bool] = None
    PlayerID: Optional[int] = None
    ProjectedOwnershipPercentage: Optional[float] = None
    SlateID: Optional[int] = None


class DfsSlateWithOwnershipProjection(BaseModel):
    Operator: Optional[str] = None
    OperatorDay: Optional[str] = None
    OperatorName: Optional[str] = None
    OperatorSlateID: Optional[int] = None
    OperatorStartTime: Optional[str] = None
    SlateID: Optional[int] = None
    SlateOwnershipProjections: Optional[List[DfsSlatePlayerOwnershipProjection]] = None


class Player(BaseModel):
    Active: Optional[bool] = None
    Age: Optional[int] = None
    AverageDraftPosition: Optional[float] = None
    BirthDate: Optional[str] = None
    BirthDateString: Optional[str] = None
    ByeWeek: Optional[int] = None
    College: Optional[str] = None
    CollegeDraftPick: Optional[int] = None
    CollegeDraftRound: Optional[int] = None
    CollegeDraftTeam: Optional[str] = None
    CollegeDraftYear: Optional[int] = None
    CurrentStatus: Optional[str] = None
    CurrentTeam: Optional[str] = None
    DeclaredInactive: Optional[bool] = None
    DepthDisplayOrder: Optional[int] = None
    DepthOrder: Optional[int] = None
    DepthPosition: Optional[str] = None
    DepthPositionCategory: Optional[str] = None
    DraftKingsName: Optional[str] = None
    DraftKingsPlayerID: Optional[int] = None
    Experience: Optional[int] = None
    ExperienceString: Optional[str] = None
    FanDuelName: Optional[str] = None
    FanDuelPlayerID: Optional[int] = None
    FantasyAlarmPlayerID: Optional[int] = None
    FantasyDraftName: Optional[str] = None
    FantasyDraftPlayerID: Optional[int] = None
    FantasyPosition: Optional[str] = None
    FantasyPositionDepthOrder: Optional[int] = None
    FirstName: Optional[str] = None
    GlobalTeamID: Optional[int] = None
    Height: Optional[str] = None
    HeightFeet: Optional[int] = None
    HeightInches: Optional[int] = None
    InjuryBodyPart: Optional[str] = None
    InjuryNotes: Optional[str] = None
    InjuryPractice: Optional[str] = None
    InjuryPracticeDescription: Optional[str] = None
    InjuryStartDate: Optional[str] = None
    InjuryStatus: Optional[str] = None
    IsUndraftedFreeAgent: Optional[bool] = None
    LastName: Optional[str] = None
    Name: Optional[str] = None
    Number: Optional[int] = None
    PhotoUrl: Optional[str] = None
    PlayerID: Optional[int] = None
    Position: Optional[str] = None
    PositionCategory: Optional[str] = None
    RotoWirePlayerID: Optional[int] = None
    RotoworldPlayerID: Optional[int] = None
    ShortName: Optional[str] = None
    SportRadarPlayerID: Optional[str] = None
    SportsDirectPlayerID: Optional[int] = None
    StatsPlayerID: Optional[int] = None
    Status: Optional[str] = None
    Team: Optional[str] = None
    TeamID: Optional[int] = None
    UpcomingDraftKingsSalary: Optional[int] = None
    UpcomingFanDuelSalary: Optional[int] = None
    UpcomingGameOpponent: Optional[str] = None
    UpcomingGameWeek: Optional[int] = None
    UpcomingOpponentPositionRank: Optional[int] = None
    UpcomingOpponentRank: Optional[int] = None
    UpcomingSalary: Optional[int] = None
    UpcomingYahooSalary: Optional[int] = None
    UsaTodayHeadshotNoBackgroundUpdated: Optional[str] = None
    UsaTodayHeadshotNoBackgroundUrl: Optional[str] = None
    UsaTodayHeadshotUpdated: Optional[str] = None
    UsaTodayHeadshotUrl: Optional[str] = None
    UsaTodayPlayerID: Optional[int] = None
    Weight: Optional[int] = None
    XmlTeamPlayerID: Optional[int] = None
    YahooName: Optional[str] = None
    YahooPlayerID: Optional[int] = None


class ScoringDetail(BaseModel):
    GameKey: Optional[str] = None
    Length: Optional[int] = None
    PlayerGameID: Optional[int] = None
    PlayerID: Optional[int] = None
    ScoreID: Optional[int] = None
    ScoringDetailID: Optional[int] = None
    ScoringPlayID: Optional[int] = None
    ScoringType: Optional[str] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    Team: Optional[str] = None
    Week: Optional[int] = None


class Stadium(BaseModel):
    Capacity: Optional[int] = None
    City: Optional[str] = None
    Country: Optional[str] = None
    GeoLat: Optional[float] = None
    GeoLong: Optional[float] = None
    Name: Optional[str] = None
    PlayingSurface: Optional[str] = None
    StadiumID: Optional[int] = None
    State: Optional[str] = None
    Type: Optional[str] = None


class Format(Enum):
    XML = 'XML'
    JSON = 'JSON'


class FieldFormatInjuredPlayersGetResponse(RootModel[List[Player]]):
    root: List[Player]


class FieldFormatUpcomingDfsSlateOwnershipProjectionsGetResponse(
    RootModel[List[DfsSlateWithOwnershipProjection]]
):
    root: List[DfsSlateWithOwnershipProjection]


class FantasyDefenseGameProjection(BaseModel):
    AssistedTackles: Optional[float] = None
    BlockedKickReturnTouchdowns: Optional[float] = None
    BlockedKickReturnYards: Optional[float] = None
    BlockedKicks: Optional[float] = None
    Date: Optional[str] = None
    DateTime: Optional[str] = None
    Day: Optional[str] = None
    DefensiveTouchdowns: Optional[float] = None
    DraftKingsFantasyPointsAllowed: Optional[float] = None
    DraftKingsKickerFantasyPointsAllowed: Optional[float] = None
    DraftKingsPosition: Optional[str] = None
    DraftKingsQuarterbackFantasyPointsAllowed: Optional[float] = None
    DraftKingsRunningbackFantasyPointsAllowed: Optional[float] = None
    DraftKingsSalary: Optional[int] = None
    DraftKingsTightEndFantasyPointsAllowed: Optional[float] = None
    DraftKingsWideReceiverFantasyPointsAllowed: Optional[float] = None
    FanDuelFantasyPointsAllowed: Optional[float] = None
    FanDuelKickerFantasyPointsAllowed: Optional[float] = None
    FanDuelPosition: Optional[str] = None
    FanDuelQuarterbackFantasyPointsAllowed: Optional[float] = None
    FanDuelRunningbackFantasyPointsAllowed: Optional[float] = None
    FanDuelSalary: Optional[int] = None
    FanDuelTightEndFantasyPointsAllowed: Optional[float] = None
    FanDuelWideReceiverFantasyPointsAllowed: Optional[float] = None
    FantasyDataSalary: Optional[int] = None
    FantasyDefenseID: Optional[int] = None
    FantasyDraftFantasyPointsAllowed: Optional[float] = None
    FantasyDraftKickerFantasyPointsAllowed: Optional[float] = None
    FantasyDraftPosition: Optional[str] = None
    FantasyDraftQuarterbackFantasyPointsAllowed: Optional[float] = None
    FantasyDraftRunningbackFantasyPointsAllowed: Optional[float] = None
    FantasyDraftSalary: Optional[int] = None
    FantasyDraftTightEndFantasyPointsAllowed: Optional[float] = None
    FantasyDraftWideReceiverFantasyPointsAllowed: Optional[float] = None
    FantasyPoints: Optional[float] = None
    FantasyPointsAllowed: Optional[float] = None
    FantasyPointsDraftKings: Optional[float] = None
    FantasyPointsFanDuel: Optional[float] = None
    FantasyPointsFantasyDraft: Optional[float] = None
    FantasyPointsYahoo: Optional[float] = None
    FieldGoalReturnTouchdowns: Optional[float] = None
    FieldGoalReturnYards: Optional[float] = None
    FourthDownAttempts: Optional[float] = None
    FourthDownConversions: Optional[float] = None
    FumbleReturnTouchdowns: Optional[float] = None
    FumbleReturnYards: Optional[float] = None
    FumblesForced: Optional[float] = None
    FumblesRecovered: Optional[float] = None
    GameKey: Optional[str] = None
    GlobalGameID: Optional[int] = None
    GlobalOpponentID: Optional[int] = None
    GlobalTeamID: Optional[int] = None
    HomeOrAway: Optional[str] = None
    Humidity: Optional[int] = None
    InterceptionReturnTouchdowns: Optional[float] = None
    InterceptionReturnYards: Optional[float] = None
    Interceptions: Optional[float] = None
    IsGameOver: Optional[bool] = None
    KickReturnLong: Optional[float] = None
    KickReturnTouchdowns: Optional[float] = None
    KickReturnYards: Optional[float] = None
    KickReturns: Optional[float] = None
    KickerFantasyPointsAllowed: Optional[float] = None
    OffensiveYardsAllowed: Optional[float] = None
    Opponent: Optional[str] = None
    OpponentID: Optional[int] = None
    OpponentPositionRank: Optional[int] = None
    OpponentRank: Optional[int] = None
    PassesDefended: Optional[float] = None
    PlayerID: Optional[int] = None
    PointsAllowed: Optional[float] = None
    PointsAllowedByDefenseSpecialTeams: Optional[float] = None
    PuntReturnLong: Optional[float] = None
    PuntReturnTouchdowns: Optional[float] = None
    PuntReturnYards: Optional[float] = None
    PuntReturns: Optional[float] = None
    QuarterbackFantasyPointsAllowed: Optional[float] = None
    QuarterbackHits: Optional[float] = None
    RunningbackFantasyPointsAllowed: Optional[float] = None
    SackYards: Optional[float] = None
    Sacks: Optional[float] = None
    Safeties: Optional[float] = None
    ScoreID: Optional[int] = None
    ScoringDetails: Optional[List[ScoringDetail]] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    SoloTackles: Optional[float] = None
    SpecialTeamsTouchdowns: Optional[float] = None
    Stadium: Optional[str] = None
    TacklesForLoss: Optional[float] = None
    Team: Optional[str] = None
    TeamID: Optional[int] = None
    Temperature: Optional[int] = None
    ThirdDownAttempts: Optional[float] = None
    ThirdDownConversions: Optional[float] = None
    TightEndFantasyPointsAllowed: Optional[float] = None
    TouchdownsScored: Optional[float] = None
    TwoPointConversionReturns: Optional[float] = None
    VictivSalary: Optional[int] = None
    Week: Optional[int] = None
    WideReceiverFantasyPointsAllowed: Optional[float] = None
    WindSpeed: Optional[int] = None
    YahooFantasyPointsAllowed: Optional[float] = None
    YahooKickerFantasyPointsAllowed: Optional[float] = None
    YahooPosition: Optional[str] = None
    YahooQuarterbackFantasyPointsAllowed: Optional[float] = None
    YahooRunningbackFantasyPointsAllowed: Optional[float] = None
    YahooSalary: Optional[int] = None
    YahooTightEndFantasyPointsAllowed: Optional[float] = None
    YahooWideReceiverFantasyPointsAllowed: Optional[float] = None


class FantasyDefenseSeasonProjection(BaseModel):
    AssistedTackles: Optional[float] = None
    AuctionValue: Optional[float] = None
    AuctionValuePPR: Optional[float] = None
    AverageDraftPosition: Optional[float] = None
    AverageDraftPosition2QB: Optional[float] = None
    AverageDraftPositionDynasty: Optional[float] = None
    AverageDraftPositionPPR: Optional[float] = None
    BlockedKickReturnTouchdowns: Optional[float] = None
    BlockedKickReturnYards: Optional[float] = None
    BlockedKicks: Optional[float] = None
    DefensiveTouchdowns: Optional[float] = None
    DraftKingsFantasyPointsAllowed: Optional[float] = None
    DraftKingsKickerFantasyPointsAllowed: Optional[float] = None
    DraftKingsQuarterbackFantasyPointsAllowed: Optional[float] = None
    DraftKingsRunningbackFantasyPointsAllowed: Optional[float] = None
    DraftKingsTightEndFantasyPointsAllowed: Optional[float] = None
    DraftKingsWideReceiverFantasyPointsAllowed: Optional[float] = None
    FanDuelFantasyPointsAllowed: Optional[float] = None
    FanDuelKickerFantasyPointsAllowed: Optional[float] = None
    FanDuelQuarterbackFantasyPointsAllowed: Optional[float] = None
    FanDuelRunningbackFantasyPointsAllowed: Optional[float] = None
    FanDuelTightEndFantasyPointsAllowed: Optional[float] = None
    FanDuelWideReceiverFantasyPointsAllowed: Optional[float] = None
    FantasyDraftFantasyPointsAllowed: Optional[float] = None
    FantasyDraftKickerFantasyPointsAllowed: Optional[float] = None
    FantasyDraftQuarterbackFantasyPointsAllowed: Optional[float] = None
    FantasyDraftRunningbackFantasyPointsAllowed: Optional[float] = None
    FantasyDraftTightEndFantasyPointsAllowed: Optional[float] = None
    FantasyDraftWideReceiverFantasyPointsAllowed: Optional[float] = None
    FantasyPoints: Optional[float] = None
    FantasyPointsAllowed: Optional[float] = None
    FantasyPointsDraftKings: Optional[float] = None
    FantasyPointsFanDuel: Optional[float] = None
    FantasyPointsFantasyDraft: Optional[float] = None
    FantasyPointsYahoo: Optional[float] = None
    FieldGoalReturnTouchdowns: Optional[float] = None
    FieldGoalReturnYards: Optional[float] = None
    FourthDownAttempts: Optional[float] = None
    FourthDownConversions: Optional[float] = None
    FumbleReturnTouchdowns: Optional[float] = None
    FumbleReturnYards: Optional[float] = None
    FumblesForced: Optional[float] = None
    FumblesRecovered: Optional[float] = None
    Games: Optional[int] = None
    GlobalTeamID: Optional[int] = None
    Humidity: Optional[int] = None
    InterceptionReturnTouchdowns: Optional[float] = None
    InterceptionReturnYards: Optional[float] = None
    Interceptions: Optional[float] = None
    KickReturnLong: Optional[float] = None
    KickReturnTouchdowns: Optional[float] = None
    KickReturnYards: Optional[float] = None
    KickReturns: Optional[float] = None
    KickerFantasyPointsAllowed: Optional[float] = None
    OffensiveYardsAllowed: Optional[float] = None
    PassesDefended: Optional[float] = None
    PlayerID: Optional[int] = None
    PointsAllowed: Optional[float] = None
    PointsAllowedByDefenseSpecialTeams: Optional[float] = None
    PuntReturnLong: Optional[float] = None
    PuntReturnTouchdowns: Optional[float] = None
    PuntReturnYards: Optional[float] = None
    PuntReturns: Optional[float] = None
    QuarterbackFantasyPointsAllowed: Optional[float] = None
    QuarterbackHits: Optional[float] = None
    RunningbackFantasyPointsAllowed: Optional[float] = None
    SackYards: Optional[float] = None
    Sacks: Optional[float] = None
    Safeties: Optional[float] = None
    ScoringDetails: Optional[List[ScoringDetail]] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    SoloTackles: Optional[float] = None
    SpecialTeamsTouchdowns: Optional[float] = None
    TacklesForLoss: Optional[float] = None
    Team: Optional[str] = None
    TeamID: Optional[int] = None
    Temperature: Optional[int] = None
    ThirdDownAttempts: Optional[float] = None
    ThirdDownConversions: Optional[float] = None
    TightEndFantasyPointsAllowed: Optional[float] = None
    TouchdownsScored: Optional[float] = None
    TwoPointConversionReturns: Optional[float] = None
    WideReceiverFantasyPointsAllowed: Optional[float] = None
    WindSpeed: Optional[int] = None
    YahooFantasyPointsAllowed: Optional[float] = None
    YahooKickerFantasyPointsAllowed: Optional[float] = None
    YahooQuarterbackFantasyPointsAllowed: Optional[float] = None
    YahooRunningbackFantasyPointsAllowed: Optional[float] = None
    YahooTightEndFantasyPointsAllowed: Optional[float] = None
    YahooWideReceiverFantasyPointsAllowed: Optional[float] = None


class PlayerGameProjection(BaseModel):
    Activated: Optional[int] = None
    AssistedTackles: Optional[float] = None
    BlockedKickReturnTouchdowns: Optional[float] = None
    BlockedKickReturnYards: Optional[float] = None
    BlockedKicks: Optional[float] = None
    DateTime: Optional[str] = None
    Day: Optional[str] = None
    DeclaredInactive: Optional[bool] = None
    DefensiveSnapsPlayed: Optional[int] = None
    DefensiveTeamSnaps: Optional[int] = None
    DefensiveTouchdowns: Optional[float] = None
    DraftKingsPosition: Optional[str] = None
    DraftKingsSalary: Optional[int] = None
    ExtraPointsAttempted: Optional[float] = None
    ExtraPointsHadBlocked: Optional[float] = None
    ExtraPointsMade: Optional[float] = None
    FanDuelPosition: Optional[str] = None
    FanDuelSalary: Optional[int] = None
    FantasyDataSalary: Optional[int] = None
    FantasyDraftPosition: Optional[str] = None
    FantasyDraftSalary: Optional[int] = None
    FantasyPoints: Optional[float] = None
    FantasyPointsDraftKings: Optional[float] = None
    FantasyPointsFanDuel: Optional[float] = None
    FantasyPointsFantasyDraft: Optional[float] = None
    FantasyPointsPPR: Optional[float] = None
    FantasyPointsYahoo: Optional[float] = None
    FantasyPosition: Optional[str] = None
    FieldGoalPercentage: Optional[float] = None
    FieldGoalReturnTouchdowns: Optional[float] = None
    FieldGoalReturnYards: Optional[float] = None
    FieldGoalsAttempted: Optional[float] = None
    FieldGoalsHadBlocked: Optional[float] = None
    FieldGoalsLongestMade: Optional[float] = None
    FieldGoalsMade: Optional[float] = None
    FieldGoalsMade0to19: Optional[float] = None
    FieldGoalsMade20to29: Optional[float] = None
    FieldGoalsMade30to39: Optional[float] = None
    FieldGoalsMade40to49: Optional[float] = None
    FieldGoalsMade50Plus: Optional[float] = None
    FumbleReturnTouchdowns: Optional[float] = None
    FumbleReturnYards: Optional[float] = None
    Fumbles: Optional[float] = None
    FumblesForced: Optional[float] = None
    FumblesLost: Optional[float] = None
    FumblesOutOfBounds: Optional[float] = None
    FumblesOwnRecoveries: Optional[float] = None
    FumblesRecovered: Optional[float] = None
    GameDate: Optional[str] = None
    GameKey: Optional[str] = None
    GlobalGameID: Optional[int] = None
    GlobalOpponentID: Optional[int] = None
    GlobalTeamID: Optional[int] = None
    HomeOrAway: Optional[str] = None
    Humidity: Optional[int] = None
    InjuryBodyPart: Optional[str] = None
    InjuryNotes: Optional[str] = None
    InjuryPractice: Optional[str] = None
    InjuryPracticeDescription: Optional[str] = None
    InjuryStartDate: Optional[str] = None
    InjuryStatus: Optional[str] = None
    InterceptionReturnTouchdowns: Optional[float] = None
    InterceptionReturnYards: Optional[float] = None
    Interceptions: Optional[float] = None
    IsGameOver: Optional[bool] = None
    KickReturnFairCatches: Optional[float] = None
    KickReturnLong: Optional[float] = None
    KickReturnTouchdowns: Optional[float] = None
    KickReturnYards: Optional[float] = None
    KickReturnYardsPerAttempt: Optional[float] = None
    KickReturns: Optional[float] = None
    MiscAssistedTackles: Optional[float] = None
    MiscFumblesForced: Optional[float] = None
    MiscFumblesRecovered: Optional[float] = None
    MiscSoloTackles: Optional[float] = None
    Name: Optional[str] = None
    Number: Optional[int] = None
    OffensiveFumbleRecoveryTouchdowns: Optional[float] = None
    OffensiveSnapsPlayed: Optional[int] = None
    OffensiveTeamSnaps: Optional[int] = None
    OffensiveTouchdowns: Optional[float] = None
    Opponent: Optional[str] = None
    OpponentID: Optional[int] = None
    OpponentPositionRank: Optional[int] = None
    OpponentRank: Optional[int] = None
    PassesDefended: Optional[float] = None
    PassingAttempts: Optional[float] = None
    PassingCompletionPercentage: Optional[float] = None
    PassingCompletions: Optional[float] = None
    PassingInterceptions: Optional[float] = None
    PassingLong: Optional[float] = None
    PassingRating: Optional[float] = None
    PassingSackYards: Optional[float] = None
    PassingSacks: Optional[float] = None
    PassingTouchdowns: Optional[float] = None
    PassingYards: Optional[float] = None
    PassingYardsPerAttempt: Optional[float] = None
    PassingYardsPerCompletion: Optional[float] = None
    Played: Optional[int] = None
    PlayerGameID: Optional[int] = None
    PlayerID: Optional[int] = None
    PlayingSurface: Optional[str] = None
    Position: Optional[str] = None
    PositionCategory: Optional[str] = None
    PuntAverage: Optional[float] = None
    PuntInside20: Optional[float] = None
    PuntLong: Optional[float] = None
    PuntNetAverage: Optional[float] = None
    PuntNetYards: Optional[float] = None
    PuntReturnFairCatches: Optional[float] = None
    PuntReturnLong: Optional[float] = None
    PuntReturnTouchdowns: Optional[float] = None
    PuntReturnYards: Optional[float] = None
    PuntReturnYardsPerAttempt: Optional[float] = None
    PuntReturns: Optional[float] = None
    PuntTouchbacks: Optional[float] = None
    PuntYards: Optional[float] = None
    Punts: Optional[float] = None
    PuntsHadBlocked: Optional[float] = None
    QuarterbackHits: Optional[float] = None
    ReceivingLong: Optional[float] = None
    ReceivingTargets: Optional[float] = None
    ReceivingTouchdowns: Optional[float] = None
    ReceivingYards: Optional[float] = None
    ReceivingYardsPerReception: Optional[float] = None
    ReceivingYardsPerTarget: Optional[float] = None
    ReceptionPercentage: Optional[float] = None
    Receptions: Optional[float] = None
    RushingAttempts: Optional[float] = None
    RushingLong: Optional[float] = None
    RushingTouchdowns: Optional[float] = None
    RushingYards: Optional[float] = None
    RushingYardsPerAttempt: Optional[float] = None
    SackYards: Optional[float] = None
    Sacks: Optional[float] = None
    Safeties: Optional[float] = None
    SafetiesAllowed: Optional[float] = None
    ScoreID: Optional[int] = None
    ScoringDetails: Optional[List[ScoringDetail]] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    ShortName: Optional[str] = None
    SnapCountsConfirmed: Optional[bool] = None
    SoloTackles: Optional[float] = None
    SpecialTeamsAssistedTackles: Optional[float] = None
    SpecialTeamsFumblesForced: Optional[float] = None
    SpecialTeamsFumblesRecovered: Optional[float] = None
    SpecialTeamsSnapsPlayed: Optional[int] = None
    SpecialTeamsSoloTackles: Optional[float] = None
    SpecialTeamsTeamSnaps: Optional[int] = None
    SpecialTeamsTouchdowns: Optional[float] = None
    Stadium: Optional[str] = None
    Started: Optional[int] = None
    Tackles: Optional[float] = None
    TacklesForLoss: Optional[float] = None
    Team: Optional[str] = None
    TeamID: Optional[int] = None
    Temperature: Optional[int] = None
    Touchdowns: Optional[float] = None
    TwoPointConversionPasses: Optional[float] = None
    TwoPointConversionReceptions: Optional[float] = None
    TwoPointConversionReturns: Optional[float] = None
    TwoPointConversionRuns: Optional[float] = None
    VictivSalary: Optional[int] = None
    Week: Optional[int] = None
    WindSpeed: Optional[int] = None
    YahooPosition: Optional[str] = None
    YahooSalary: Optional[int] = None


class PlayerSeasonProjection(BaseModel):
    Activated: Optional[int] = None
    AssistedTackles: Optional[float] = None
    AuctionValue: Optional[float] = None
    AuctionValuePPR: Optional[float] = None
    AverageDraftPosition: Optional[float] = None
    AverageDraftPosition2QB: Optional[float] = None
    AverageDraftPositionDynasty: Optional[float] = None
    AverageDraftPositionPPR: Optional[float] = None
    AverageDraftPositionRookie: Optional[float] = None
    BlockedKickReturnTouchdowns: Optional[float] = None
    BlockedKickReturnYards: Optional[float] = None
    BlockedKicks: Optional[float] = None
    DefensiveSnapsPlayed: Optional[int] = None
    DefensiveTeamSnaps: Optional[int] = None
    DefensiveTouchdowns: Optional[float] = None
    ExtraPointsAttempted: Optional[float] = None
    ExtraPointsHadBlocked: Optional[float] = None
    ExtraPointsMade: Optional[float] = None
    FantasyPoints: Optional[float] = None
    FantasyPointsDraftKings: Optional[float] = None
    FantasyPointsFanDuel: Optional[float] = None
    FantasyPointsFantasyDraft: Optional[float] = None
    FantasyPointsPPR: Optional[float] = None
    FantasyPointsYahoo: Optional[float] = None
    FantasyPosition: Optional[str] = None
    FieldGoalPercentage: Optional[float] = None
    FieldGoalReturnTouchdowns: Optional[float] = None
    FieldGoalReturnYards: Optional[float] = None
    FieldGoalsAttempted: Optional[float] = None
    FieldGoalsHadBlocked: Optional[float] = None
    FieldGoalsLongestMade: Optional[float] = None
    FieldGoalsMade: Optional[float] = None
    FieldGoalsMade0to19: Optional[float] = None
    FieldGoalsMade20to29: Optional[float] = None
    FieldGoalsMade30to39: Optional[float] = None
    FieldGoalsMade40to49: Optional[float] = None
    FieldGoalsMade50Plus: Optional[float] = None
    FumbleReturnTouchdowns: Optional[float] = None
    FumbleReturnYards: Optional[float] = None
    Fumbles: Optional[float] = None
    FumblesForced: Optional[float] = None
    FumblesLost: Optional[float] = None
    FumblesOutOfBounds: Optional[float] = None
    FumblesOwnRecoveries: Optional[float] = None
    FumblesRecovered: Optional[float] = None
    GlobalTeamID: Optional[int] = None
    Humidity: Optional[int] = None
    InterceptionReturnTouchdowns: Optional[float] = None
    InterceptionReturnYards: Optional[float] = None
    Interceptions: Optional[float] = None
    KickReturnFairCatches: Optional[float] = None
    KickReturnLong: Optional[float] = None
    KickReturnTouchdowns: Optional[float] = None
    KickReturnYards: Optional[float] = None
    KickReturnYardsPerAttempt: Optional[float] = None
    KickReturns: Optional[float] = None
    MiscAssistedTackles: Optional[float] = None
    MiscFumblesForced: Optional[float] = None
    MiscFumblesRecovered: Optional[float] = None
    MiscSoloTackles: Optional[float] = None
    Name: Optional[str] = None
    Number: Optional[int] = None
    OffensiveFumbleRecoveryTouchdowns: Optional[int] = None
    OffensiveSnapsPlayed: Optional[int] = None
    OffensiveTeamSnaps: Optional[int] = None
    OffensiveTouchdowns: Optional[float] = None
    PassesDefended: Optional[float] = None
    PassingAttempts: Optional[float] = None
    PassingCompletionPercentage: Optional[float] = None
    PassingCompletions: Optional[float] = None
    PassingInterceptions: Optional[float] = None
    PassingLong: Optional[float] = None
    PassingRating: Optional[float] = None
    PassingSackYards: Optional[float] = None
    PassingSacks: Optional[float] = None
    PassingTouchdowns: Optional[float] = None
    PassingYards: Optional[float] = None
    PassingYardsPerAttempt: Optional[float] = None
    PassingYardsPerCompletion: Optional[float] = None
    Played: Optional[int] = None
    PlayerID: Optional[int] = None
    PlayerSeasonID: Optional[int] = None
    Position: Optional[str] = None
    PositionCategory: Optional[str] = None
    PuntAverage: Optional[float] = None
    PuntInside20: Optional[float] = None
    PuntLong: Optional[float] = None
    PuntNetAverage: Optional[float] = None
    PuntNetYards: Optional[float] = None
    PuntReturnFairCatches: Optional[float] = None
    PuntReturnLong: Optional[float] = None
    PuntReturnTouchdowns: Optional[float] = None
    PuntReturnYards: Optional[float] = None
    PuntReturnYardsPerAttempt: Optional[float] = None
    PuntReturns: Optional[float] = None
    PuntTouchbacks: Optional[float] = None
    PuntYards: Optional[float] = None
    Punts: Optional[float] = None
    PuntsHadBlocked: Optional[float] = None
    QuarterbackHits: Optional[float] = None
    ReceivingLong: Optional[float] = None
    ReceivingTargets: Optional[float] = None
    ReceivingTouchdowns: Optional[float] = None
    ReceivingYards: Optional[float] = None
    ReceivingYardsPerReception: Optional[float] = None
    ReceivingYardsPerTarget: Optional[float] = None
    ReceptionPercentage: Optional[float] = None
    Receptions: Optional[float] = None
    RushingAttempts: Optional[float] = None
    RushingLong: Optional[float] = None
    RushingTouchdowns: Optional[float] = None
    RushingYards: Optional[float] = None
    RushingYardsPerAttempt: Optional[float] = None
    SackYards: Optional[float] = None
    Sacks: Optional[float] = None
    Safeties: Optional[float] = None
    SafetiesAllowed: Optional[float] = None
    ScoringDetails: Optional[List[ScoringDetail]] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    ShortName: Optional[str] = None
    SoloTackles: Optional[float] = None
    SpecialTeamsAssistedTackles: Optional[float] = None
    SpecialTeamsFumblesForced: Optional[float] = None
    SpecialTeamsFumblesRecovered: Optional[float] = None
    SpecialTeamsSnapsPlayed: Optional[int] = None
    SpecialTeamsSoloTackles: Optional[float] = None
    SpecialTeamsTeamSnaps: Optional[int] = None
    SpecialTeamsTouchdowns: Optional[float] = None
    Started: Optional[int] = None
    Tackles: Optional[float] = None
    TacklesForLoss: Optional[float] = None
    Team: Optional[str] = None
    TeamID: Optional[int] = None
    Temperature: Optional[int] = None
    Touchdowns: Optional[float] = None
    TwoPointConversionPasses: Optional[float] = None
    TwoPointConversionReceptions: Optional[float] = None
    TwoPointConversionReturns: Optional[float] = None
    TwoPointConversionRuns: Optional[float] = None
    WindSpeed: Optional[int] = None


class Schedule(BaseModel):
    AwayTeam: Optional[str] = None
    AwayTeamMoneyLine: Optional[int] = None
    Canceled: Optional[bool] = None
    Channel: Optional[str] = None
    Date: Optional[str] = None
    DateTime: Optional[str] = None
    Day: Optional[str] = None
    ForecastDescription: Optional[str] = None
    ForecastTempHigh: Optional[int] = None
    ForecastTempLow: Optional[int] = None
    ForecastWindChill: Optional[int] = None
    ForecastWindSpeed: Optional[int] = None
    GameKey: Optional[str] = None
    GeoLat: Optional[float] = None
    GeoLong: Optional[float] = None
    GlobalAwayTeamID: Optional[int] = None
    GlobalGameID: Optional[int] = None
    GlobalHomeTeamID: Optional[int] = None
    HomeTeam: Optional[str] = None
    HomeTeamMoneyLine: Optional[int] = None
    OverUnder: Optional[float] = None
    PointSpread: Optional[float] = None
    ScoreID: Optional[int] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    StadiumDetails: Optional[Stadium] = None
    StadiumID: Optional[int] = None
    Status: Optional[str] = None
    Week: Optional[int] = None


class FieldFormatFantasyDefenseProjectionsByGameSeasonWeekGetResponse(
    RootModel[List[FantasyDefenseGameProjection]]
):
    root: List[FantasyDefenseGameProjection]


class FieldFormatFantasyDefenseProjectionsBySeasonSeasonGetResponse(
    RootModel[List[FantasyDefenseSeasonProjection]]
):
    root: List[FantasyDefenseSeasonProjection]


class FieldFormatIdpPlayerGameProjectionStatsByTeamSeasonWeekTeamGetResponse(
    RootModel[List[PlayerGameProjection]]
):
    root: List[PlayerGameProjection]


class FieldFormatIdpPlayerGameProjectionStatsByWeekSeasonWeekGetResponse(
    RootModel[List[PlayerGameProjection]]
):
    root: List[PlayerGameProjection]


class FieldFormatPlayerGameProjectionStatsByTeamSeasonWeekTeamGetResponse(
    RootModel[List[PlayerGameProjection]]
):
    root: List[PlayerGameProjection]


class FieldFormatPlayerGameProjectionStatsByWeekSeasonWeekGetResponse(
    RootModel[List[PlayerGameProjection]]
):
    root: List[PlayerGameProjection]


class FieldFormatPlayerSeasonProjectionStatsSeasonGetResponse(
    RootModel[List[PlayerSeasonProjection]]
):
    root: List[PlayerSeasonProjection]


class FieldFormatPlayerSeasonProjectionStatsByTeamSeasonTeamGetResponse(
    RootModel[List[PlayerSeasonProjection]]
):
    root: List[PlayerSeasonProjection]


class DfsSlateGame(BaseModel):
    Game: Optional[Schedule] = None
    GameID: Optional[int] = None
    OperatorGameID: Optional[int] = None
    RemovedByOperator: Optional[bool] = None
    ScoreID: Optional[int] = None
    SlateGameID: Optional[int] = None
    SlateID: Optional[int] = None


class DfsSlate(BaseModel):
    DfsSlateGames: Optional[List[DfsSlateGame]] = None
    DfsSlatePlayers: Optional[List[DfsSlatePlayer]] = None
    IsMultiDaySlate: Optional[bool] = None
    NumberOfGames: Optional[int] = None
    Operator: Optional[str] = None
    OperatorDay: Optional[str] = None
    OperatorGameType: Optional[str] = None
    OperatorName: Optional[str] = None
    OperatorSlateID: Optional[int] = None
    OperatorStartTime: Optional[str] = None
    RemovedByOperator: Optional[bool] = None
    SalaryCap: Optional[int] = None
    SlateID: Optional[int] = None
    SlateRosterSlots: Optional[List[str]] = None


class FieldFormatDfsSlatesByDateDateGetResponse(RootModel[List[DfsSlate]]):
    root: List[DfsSlate]


class FieldFormatDfsSlatesByWeekSeasonWeekGetResponse(RootModel[List[DfsSlate]]):
    root: List[DfsSlate]
